/**
 * 单位建造列表代码
 */
module.exports = [
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Minigun',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Missile',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : chopper',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Harvester',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Lifter',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_CURRENTPLAYER \n  AIS_UNITTYPE_SPECIFIC : HeavyTank',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Ransom',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Borden',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Madsen',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Sinclair',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Kroker',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Patton',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Korolev',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Elroy',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : soulunit',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : scavunit',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : armour',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Cooler',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Supertank',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Superchopper',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Hovertank',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Shield',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Flamer',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_CURRENTPLAYER \n  AIS_UNITTYPE_SPECIFIC : Lobber',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_CURRENTPLAYER \n  AIS_UNITTYPE_SPECIFIC : EMP',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Cloak',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Reconbuggy',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Staticplatform',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Laser',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Repair',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : carrierguns',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Kenzie',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Lazare',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Bomber',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Supertank',
  'Action: AIScript_MakeAvailableForBuilding\n  AIS_SPECIFICPLAYER : 0\n  AIS_UNITTYPE_SPECIFIC : Superhover',
]